nelmio_cors:
    defaults:
        allow_credentials: true
        origin_regex: true
        allow_origin:
            - '^http://localhost(:[0-9]+)?$'
            - '^http://127\.0\.0\.1(:[0-9]+)?$'
            - '^http://192\.168\.1\.16(:[0-9]+)?$'
            - '^exp://.*$'
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        expose_headers: ['Link']
        max_age: 3600

    paths:
        '^/api/':
            allow_credentials: true
            origin_regex: true
            allow_origin:
                - '^http://localhost(:[0-9]+)?$'
                - '^http://127\.0\.0\.1(:[0-9]+)?$'
                - '^http://192\.168\.1\.16(:[0-9]+)?$'
                - '^exp://.*$'
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
